# Generated by Django 4.0 on 2021-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_rollnumber', models.IntegerField()),
                ('student_class', models.IntegerField()),
            ],
        ),
    ]
