# Generated by Django 4.0 on 2021-12-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASS_name', models.IntegerField()),
                ('CLASS_id', models.IntegerField()),
                ('CLASS_teacher', models.CharField(max_length=200)),
            ],
        ),
    ]
